apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-demo
  template:
    metadata:
      labels:
        app: backend-demo
    spec:
      containers:
        - name: backend
          image: kondrahin/kuber_demo_backend:latest
          ports:
          - containerPort: 8000
          env:
          - name: POSTGRES_DSN
            value: "postgresql+asyncpg://demo:demo@demo-database-postgresql.default.svc.cluster.local:5432/demo"
