apiVersion: v1
kind: Service # Create service
metadata:
  name: frontend # Sets the service name
  labels:
    app: frontend-demo # Defines app to create service for
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: frontend-demo
